CREATE TABLE ECOMMERCE_DB.ANALYTICS.CLEAN_CUSTOMERS AS
SELECT
    customer_id,
    UPPER(TRIM(customer_name)) AS customer_name,
    LOWER(TRIM(email)) AS email,
    UPPER(TRIM(country)) AS country
FROM ECOMMERCE_DB.RAW.CUSTOMERS;

SELECT * 
FROM ECOMMERCE_DB.ANALYTICS.CLEAN_CUSTOMERS;
