-- Analytics Layer

USE DATABASE ECOMMERCE_DB;

-- Create Analytics Schema
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

USE SCHEMA ANALYTICS;


-- 1. Customer Sales Summary
CREATE OR REPLACE TABLE CUSTOMER_SALES_SUMMARY AS
SELECT
    CUSTOMER,
    COUNT(*) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    SUM(TOTAL_AMOUNT) AS TOTAL_SPENT,
    AVG(TOTAL_AMOUNT) AS AVERAGE_ORDER_VALUE
FROM RAW.SALES
GROUP BY CUSTOMER;


-- 2. Product Sales Summary
CREATE OR REPLACE TABLE PRODUCT_SALES_SUMMARY AS
SELECT
    PRODUCT,
    COUNT(*) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
    AVG(PRICE) AS AVERAGE_PRICE
FROM RAW.SALES
GROUP BY PRODUCT;


-- 3. Overall Sales Summary
CREATE OR REPLACE TABLE SALES_SUMMARY AS
SELECT
    COUNT(*) AS TOTAL_ORDERS,
    SUM(QUANTITY) AS TOTAL_QUANTITY,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
    AVG(TOTAL_AMOUNT) AS AVERAGE_ORDER_VALUE
FROM RAW.SALES;