-- Dashboard Data Layer

USE DATABASE ECOMMERCE_DB;
USE SCHEMA ANALYTICS;


-- 1. Customer Dashboard
CREATE OR REPLACE TABLE DASHBOARD_CUSTOMER AS
SELECT *
FROM CUSTOMER_SALES_SUMMARY
ORDER BY TOTAL_SPENT DESC;


-- 2. Product Dashboard
CREATE OR REPLACE TABLE DASHBOARD_PRODUCT AS
SELECT *
FROM PRODUCT_SALES_SUMMARY
ORDER BY TOTAL_REVENUE DESC;


-- 3. Sales Dashboard
CREATE OR REPLACE TABLE DASHBOARD_SALES AS
SELECT *
FROM SALES_SUMMARY;