-- Verify Analytics Layer

USE DATABASE ECOMMERCE_DB;
USE SCHEMA ANALYTICS;


-- Verify Customer Analytics
SELECT *
FROM CUSTOMER_SALES_SUMMARY
ORDER BY TOTAL_SPENT DESC;


-- Verify Product Analytics
SELECT *
FROM PRODUCT_SALES_SUMMARY
ORDER BY TOTAL_REVENUE DESC;


-- Verify Overall Sales
SELECT *
FROM SALES_SUMMARY;